# Clippy linter configuration
# https://rust-lang.github.io/rust-clippy/

# Disallow certain warnings
disallowed-methods = [
    { name = "unwrap", allow-invalid = true },
]

# Minimum Supported Rust Version
msrv = "1.75"
